version: 2
jobs:
  checkout_and_install:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}-
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: npm install --quiet
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build
  lint:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/build
    steps:
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: npm run lint
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/build
    steps:
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: completed-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build
  test:
    docker:
      - image: circleci/node:9.11.1
      - image: dydxprotocol/protocol:v0.2.4
    working_directory: ~/build
    steps:
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Wait for contracts to be deployed
          command: sleep 15
      - run:
          name: Test
          command: npm test
  publish:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/build
    steps:
      - restore_cache:
          key: completed-build-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - "94:6a:1c:a9:10:70:65:45:5f:a9:1c:8b:ec:fa:ca:ec"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/build/.npmrc
      - run:
          command: sh scripts/publish_if_not_exists.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_and_install
      - test:
          requires:
            - checkout_and_install
      - lint:
          requires:
            - checkout_and_install
      - build:
          requires:
            - checkout_and_install
      - publish:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: master
